development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rss_reader_dev
  pool: 5
  username: postgres
  password: postgres

test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rss_reader_test
  pool: 5
  username: postgres
  password: postgres


production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rss_reader
  pool: 5
  username: postgres
  password: postgres

cucumber:
  <<: *test